In [1]:
%load_ext autoreload
%autoreload 2

import sys
import os

import pandas as pd
import joblib
import json
import numpy as np

sys.path.append("..")

In [2]:
from alternative_image_clustering.data.dataset import Dataset

datasets = [
    "cards",
    "fruits360",
    "gtsrb",
    "nrobjects"
]

base_dir = "/mnt/data/stephana93dm/storage/projects/alternative_image_clustering"
dset = Dataset(
    base_dir=base_dir,
    dataset_name="nrobjects",
    embedding_type= "tfidf"
)

/mnt/data/stephana93dm/storage/conda_envs/alternative_clustering/lib/python3.11/site-packages/transformers/utils/hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(


In [25]:
from alternative_image_clustering.experiments.run_all import run_image_experiments, run_baseline_kmeans


res = run_image_experiments(dataset="nrobjects", base_dir=base_dir)

In [26]:
res

{'kmeans': {'shape': {'inertia': 511170.6219745354,
   'labels': array([2, 1, 2, ..., 0, 2, 2], dtype=int32),
   'random_state': 32,
   'metrics': {'AMI': 0.9622259879359462,
    'NMI': 0.9622334155739896,
    'ARI': 0.952824320754351,
    'ACC': 0.9666}},
  'material': {'inertia': 637519.4204628995,
   'labels': array([0, 1, 0, ..., 0, 0, 0], dtype=int32),
   'random_state': 32,
   'metrics': {'AMI': 1.3888329333587243e-06,
    'NMI': 7.672896847426471e-05,
    'ARI': 5.062455685603226e-05,
    'ACC': 0.50527}},
  'colour': {'inertia': 409588.79298877175,
   'labels': array([1, 4, 1, ..., 0, 1, 1], dtype=int32),
   'random_state': 835,
   'metrics': {'AMI': 0.21732158509976846,
    'NMI': 0.21788569218535786,
    'ARI': 0.09709911809072401,
    'ACC': 0.30744000000000005}}},
 'nrkmeans': {}}

In [29]:
per_prompt_performance = run_baseline_kmeans(base_dir=base_dir, dataset="nrobjects", embedding_type="sbert_concat")

Running kmeans on full embeddings for each category
Running kmeans for each prompt
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
(10000, 1024) 10000
Transforming to average and max. performance
Computing per category performance


In [31]:
per_prompt_performance

({'material': {'AMI': 0.15024724754384808,
   'NMI': 0.15031358142120102,
   'ARI': 0.14834249699605492,
   'ACC': 0.6355733333333334},
  'shape': {'AMI': 0.7936399029852245,
   'NMI': 0.7936781735886144,
   'ARI': 0.7585725131193963,
   'ACC': 0.8676999999999998},
  'colour': {'AMI': 0.8828091066115014,
   'NMI': 0.8828920435107835,
   'ARI': 0.8122647237808498,
   'ACC': 0.880875}},
 {'material': {'AMI': 0.4055749454436882,
   'NMI': 0.40562405138635793,
   'ARI': 0.3721448098784884,
   'ACC': 0.7770500000000001},
  'shape': {'AMI': 0.9991697939094195,
   'NMI': 0.9991699450942368,
   'ARI': 0.9996979154804484,
   'ACC': 0.9999},
  'colour': {'AMI': 0.9515948288749121,
   'NMI': 0.9516287661939875,
   'ARI': 0.9269009680544787,
   'ACC': 0.9621500000000001}},
 {'shape': {'inertia': 448.8343811035156,
   'labels': array([1, 2, 1, ..., 0, 1, 1], dtype=int32),
   'random_state': 32,
   'metrics': {'AMI': 1.0, 'NMI': 1.0, 'ARI': 1.0, 'ACC': 1.0}},
  'material': {'inertia': 562.3531494140

In [20]:
per_prompt_performance

({'type': {'AMI': 0.5553747931982943,
   'NMI': 0.5555992729503831,
   'ARI': 0.4974141510675672,
   'ACC': 0.6770089285714286},
  'colour': {'AMI': 0.8274598604992264,
   'NMI': 0.8274784324112351,
   'ARI': 0.8850765465359106,
   'ACC': 0.9703621031746031}},
 {'type': {'AMI': 0.6100758125048855,
   'NMI': 0.6102733294253279,
   'ARI': 0.5648056805302125,
   'ACC': 0.7426488095238095},
  'colour': {'AMI': 0.8530328091044186,
   'NMI': 0.8530486245666111,
   'ARI': 0.9104206484895829,
   'ACC': 0.9770833333333331}},
 {'type': {'inertia': 262.6256408691406,
   'labels': array([1, 1, 0, ..., 2, 1, 1], dtype=int32),
   'random_state': 732,
   'metrics': {'AMI': 0.6256338754262021,
    'NMI': 0.625818726052952,
    'ARI': 0.5708905207805037,
    'ACC': 0.7617857142857143}},
  'colour': {'inertia': 124.3109130859375,
   'labels': array([0, 0, 1, ..., 1, 0, 0], dtype=int32),
   'random_state': 32,
   'metrics': {'AMI': 0.8448822154877471,
    'NMI': 0.8448989064584758,
    'ARI': 0.899659606

In [13]:
embeddings = dset.get_embeddings()[0:400]

In [15]:
embeddings

array([[0.        , 0.        , 0.02935825, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.05509474, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.0566842 , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.07742015, ..., 0.        , 0.        ,
        0.        ]])

In [8]:
n_clusters

[3, 2, 6]

In [16]:
from clustpy.alternative import NrKmeans

n_clusters_per_category = dset.get_n_clusters_per_category()
n_clusters = list(n_clusters_per_category.values())

nrkmeans = NrKmeans(n_clusters=n_clusters, n_init=1, max_iter=300, random_state=42).fit(embeddings)


KeyboardInterrupt: 

In [13]:
out = nrkmeans.labels_

In [59]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.array([a, b]).T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [60]:
from alternative_image_clustering.metrics import get_metrics

labels_true = []
for idx, category in enumerate(dset.get_categories()):
    labels = dset.get_clustering_labels(category)
    labels_true.append(labels)
    print(len(labels), out[:, idx].shape)
    metrics = get_metrics(labels, out[:, idx])
    print(metrics)

labels_true = np.array(labels_true).T
labels_true

400 (400,)
{'AMI': 0.5931192987904808, 'NMI': 0.595000111495611, 'ARI': 0.5242472112325053, 'ACC': 0.715}
400 (400,)
{'AMI': -0.0007779470133809954, 'NMI': 0.0011071493380167882, 'ARI': 0.0007992170409365663, 'ACC': 0.53}
400 (400,)
{'AMI': 0.0569861961977826, 'NMI': 0.07397841288703175, 'ARI': 0.03481931069903229, 'ACC': 0.265}


array([[1, 0, 1],
       [2, 0, 0],
       [1, 0, 0],
       ...,
       [2, 1, 5],
       [2, 1, 4],
       [0, 0, 0]])

In [63]:
dset.get_full_clustering_labels() == labels_true

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       ...,
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [15]:
labels_true.shape

(400, 3)

In [49]:
from clustpy.metrics.multipe_labelings_scoring import MultipleLabelingsConfusionMatrix
from sklearn.metrics import normalized_mutual_info_score, adjusted_mutual_info_score
from clustpy.metrics.clustering_metrics import unsupervised_clustering_accuracy

# confusion matrix dimensions: labels_true.shape[1], labels_pred.shape[1]
matrix = MultipleLabelingsConfusionMatrix(labels_true=labels_true, labels_pred=out, metric=normalized_mutual_info_score)
matrix.confusion_matrix

# if matrix.confusion_matrix[0,0]+ matrix.confusion_matrix[1,1] < matrix.confusion_matrix[0,1]+ matrix.confusion_matrix[1,0]:
    

array([[0.59500011, 0.73840737, 0.76764658],
       [0.00109346, 0.00110715, 0.13274928],
       [0.03566391, 0.00474684, 0.07397841]])

In [36]:
5.931e-01

0.5931

In [46]:
matrix.confusion_matrix.max(axis=1)


array([0.76764658, 0.13274928, 0.07397841])

In [47]:
matrix.rearrange().diagonal()

array([0.73840737, 0.13274928, 0.03566391])

In [48]:
from alternative_image_clustering.metrics import get_multiple_labeling_metrics

labels_true = dset.get_full_clustering_labels()
get_multiple_labeling_metrics(labels_true, out, dset.get_categories())

{'shape': {'AMI': 0.7376494269198355,
  'NMI': 0.7384073699321148,
  'ARI': 0.5807731815001658,
  'ACC': 0.715},
 'material': {'AMI': 0.12826463150509856,
  'NMI': 0.13274927819718388,
  'ARI': 0.07622175411674632,
  'ACC': 0.53},
 'colour': {'AMI': 0.027081005735636765,
  'NMI': 0.035663905970405745,
  'ARI': 0.017892506603905973,
  'ACC': 0.265}}

In [ ]:
# goal find i_1, .., i_n s.th. sum(matrix[1, i_1], .., matrix[1, i_n]) is maximized
# and i_1, .., i_n are unique

In [71]:
from itertools import permutations

from sklearn.metrics import confusion_matrix


def get_best_assignment_metrics(matrix, categories):
    all_permutations = list(permutations(range(len(categories)), len(categories)))

    scores = {}
    for permutation in all_permutations:
        score = 0
        for i in range(3):
            score += matrix.confusion_matrix[permutation[i], i]
        scores[permutation] = score

    best_permutation = max(scores, key=scores.get)

    return {category: matrix.confusion_matrix[best_permutation[idx], idx] for idx, category in enumerate(categories)}


categories = dset.get_categories()
get_best_assignment_metrics(matrix, categories)



{'shape': 0.3326, 'material': 0.9528, 'colour': 0.7593}

In [56]:
all_permutations[0]

(0, 1, 2)

In [58]:
matrix.confusion_matrix[0,0]  + matrix.confusion_matrix[1,1] + matrix.confusion_matrix[2,2]


0.3747

In [60]:
matrix.confusion_matrix[0,1] 

0.3719

In [49]:
matrix.confusion_matrix

array([[0.3747, 0.3719, 0.7593],
       [0.4513, 0.9528, 0.3276],
       [0.3326, 0.1982, 0.2354]])

In [43]:
from alternative_image_clustering.metrics import get_metrics

metrics = get_metrics(labels, labels_pred)
metrics

{'AMI': 0.4103981332427923,
 'ARI': 0.2699533462935888,
 'ACC': 0.49361614497528833}